server:
  error:
    include-message: always
    include-binding-errors: always
jwt:
  secret: yourSecretKey
  expiration: 86400

spring:
  datasource:
    password: dbpassword
    url: jdbc:mysql://localhost:3306/corpU?serverTimezone=UTC
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

  mail:
    host: localhost
    #MailDev SMTP Server running at 0.0.0.0:1025
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000